parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Application\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }
        App\Application\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        App\Application\Event\EventHandler:
            tags:
                - { name: messenger.message_handler, bus: event.bus }
